# Generated by Django 6.0.5 on 2026-05-29 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ordem', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ordem', models.PositiveIntegerField()),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodadas', to='core.fase')),
            ],
            options={
                'ordering': ['fase__ordem', 'ordem'],
                'unique_together': {('fase', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_jogo', models.PositiveIntegerField(blank=True, null=True)),
                ('data_jogo', models.DateTimeField()),
                ('estadio', models.CharField(blank=True, max_length=150)),
                ('gols_casa', models.IntegerField(blank=True, null=True)),
                ('gols_fora', models.IntegerField(blank=True, null=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='core.fase')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='core.grupo')),
                ('rodada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='core.rodada')),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_casa', to='core.time')),
                ('time_fora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_fora', to='core.time')),
            ],
            options={
                'ordering': ['data_jogo'],
                'unique_together': {('time_casa', 'time_fora', 'data_jogo')},
            },
        ),
        migrations.CreateModel(
            name='Palpite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_casa', models.IntegerField()),
                ('gols_fora', models.IntegerField()),
                ('pontos', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpites', to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpites', to='core.partida')),
            ],
            options={
                'unique_together': {('usuario', 'partida')},
            },
        ),
    ]
