# Generated by Django 6.0.5 on 2026-05-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palpite',
            name='placar_exato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='palpite',
            name='vencedor_correto',
            field=models.BooleanField(default=False),
        ),
    ]
