# Generated by Django 6.0.5 on 2026-05-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_palpite_placar_exato_palpite_vencedor_correto'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='bandeira',
            field=models.ImageField(blank=True, null=True, upload_to='bandeiras/'),
        ),
    ]
