# Generated by Django 6.0.5 on 2026-05-30 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_time_bandeira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='time_casa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas_casa', to='core.time'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='time_fora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas_fora', to='core.time'),
        ),
    ]
