# Generated by Django 6.0.5 on 2026-06-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gruporanking_participantegruporanking'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='penaltis_casa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='penaltis_fora',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
